/* eslint-disable sort-keys */
/* File:      Vk.ts
 * Author:    Gage Sorrell <gsorrell@purdue.edu>
 * Copyright: (c) 2023 Gage Sorrell
 * License:   MIT
 */

import { FDomKey } from "../Component/Key/Key.Types";

export type FVkUnstyled =
    | "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "A"
    | "B"
    | "C"
    | "D"
    | "E"
    | "F"
    | "F1"
    | "F2"
    | "F3"
    | "F4"
    | "F5"
    | "F6"
    | "F7"
    | "F8"
    | "F9"
    | "F10"
    | "F11"
    | "F12"
    | "F13"
    | "F14"
    | "F15"
    | "F16"
    | "F17"
    | "F18"
    | "F19"
    | "F20"
    | "F21"
    | "F22"
    | "F23"
    | "F24"
    | "G"
    | "H"
    | "I"
    | "J"
    | "K"
    | "L"
    | "M"
    | "N"
    | "O"
    | "P"
    | "Q"
    | "R"
    | "S"
    | "T"
    | "U"
    | "V"
    | "W"
    | "X"
    | "Y"
    | "End"
    | "Home"
    | "Z";

// eslint-disable-next-line @typescript-eslint/naming-convention
export type VK =
    | FVkUnstyled
    | "LButton"
    | "RButton"
    | "MButton"
    | "XButton1"
    | "XButton2"
    | "Back"
    | "Tab"
    | "Return"
    | "Shift"
    | "Control"
    | "Menu"
    | "Pause"
    | "Capital"
    | "Space"
    | "Prior"
    | "Next"
    | "Left"
    | "Up"
    | "Right"
    | "Down"
    | "Select"
    | "Print"
    | "Snapshot"
    | "Insert"
    | "Delete"
    | "LWin"
    | "RWin"
    | "Apps"
    | "NumPad0"
    | "NumPad1"
    | "NumPad2"
    | "NumPad3"
    | "NumPad4"
    | "NumPad5"
    | "NumPad6"
    | "NumPad7"
    | "NumPad8"
    | "NumPad9"
    | "Multiply"
    | "Add"
    | "Separator"
    | "Subtract"
    | "Decimal"
    | "Divide"
    | "NumLock"
    | "Scroll"
    | "LShift"
    | "RShift"
    | "LControl"
    | "RControl"
    | "LMenu"
    | "RMenu"
    | "BrowserBack"
    | "BrowserForward"
    | "BrowserRefresh"
    | "BrowserStop"
    | "BrowserSearch"
    | "BrowserFavorites"
    | "BrowserHome"
    | "VolumeMute"
    | "VolumeDown"
    | "VolumeUp"
    | "MediaNextTrack"
    | "MediaPrevTrack"
    | "MediaStop"
    | "LaunchMail"
    | "LaunchMediaSelect"
    | "LaunchApp1"
    | "LaunchApp2"
    | "Oem1"
    | "OemPlus"
    | "OemComma"
    | "OemMinus"
    | "OemPeriod"
    | "Oem2"
    | "Oem3"
    | "Oem4"
    | "Oem5"
    | "Oem6"
    | "Oem7";

export const Vk: { [ Key in VK ]: number } =
{
    LButton: 0x01,
    RButton: 0x02,
    MButton: 0x04,
    XButton1: 0x05,
    XButton2: 0x06,
    Back: 0x08,
    Tab: 0x09,
    Return: 0x0D,
    Shift: 0x10,
    Control: 0x11,
    Menu: 0x12,
    Pause: 0x13,
    Capital: 0x14,
    Space: 0x20,
    Prior: 0x21,
    Next: 0x22,
    End: 0x23,
    Home: 0x24,
    Left: 0x25,
    Up: 0x26,
    Right: 0x27,
    Down: 0x28,
    Select: 0x29,
    Print: 0x2A,
    Snapshot: 0x2C,
    Insert: 0x2D,
    Delete: 0x2E,
    "0": 0x30,
    "1": 0x31,
    "2": 0x32,
    "3": 0x33,
    "4": 0x34,
    "5": 0x35,
    "6": 0x36,
    "7": 0x37,
    "8": 0x38,
    "9": 0x39,
    A: 0x41,
    B: 0x42,
    C: 0x43,
    D: 0x44,
    E: 0x45,
    F: 0x46,
    G: 0x47,
    H: 0x48,
    I: 0x49,
    J: 0x4A,
    K: 0x4B,
    L: 0x4C,
    M: 0x4D,
    N: 0x4E,
    O: 0x4F,
    P: 0x50,
    Q: 0x51,
    R: 0x52,
    S: 0x53,
    T: 0x54,
    U: 0x55,
    V: 0x56,
    W: 0x57,
    X: 0x58,
    Y: 0x59,
    Z: 0x5A,
    LWin: 0x5B,
    RWin: 0x5C,
    Apps: 0x5D,
    NumPad0: 0x60,
    NumPad1: 0x61,
    NumPad2: 0x62,
    NumPad3: 0x63,
    NumPad4: 0x64,
    NumPad5: 0x65,
    NumPad6: 0x66,
    NumPad7: 0x67,
    NumPad8: 0x68,
    NumPad9: 0x69,
    Multiply: 0x6A,
    Add: 0x6B,
    Separator: 0x6C,
    Subtract: 0x6D,
    Decimal: 0x6E,
    Divide: 0x6F,
    F1: 0x70,
    F2: 0x71,
    F3: 0x72,
    F4: 0x73,
    F5: 0x74,
    F6: 0x75,
    F7: 0x76,
    F8: 0x77,
    F9: 0x78,
    F10: 0x79,
    F11: 0x7A,
    F12: 0x7B,
    F13: 0x7C,
    F14: 0x7D,
    F15: 0x7E,
    F16: 0x7F,
    F17: 0x80,
    F18: 0x81,
    F19: 0x82,
    F20: 0x83,
    F21: 0x84,
    F22: 0x85,
    F23: 0x86,
    F24: 0x87,
    NumLock: 0x90,
    Scroll: 0x91,
    LShift: 0xA0,
    RShift: 0xA1,
    LControl: 0xA2,
    RControl: 0xA3,
    LMenu: 0xA4,
    RMenu: 0xA5,
    BrowserBack: 0xA6,
    BrowserForward: 0xA7,
    BrowserRefresh: 0xA8,
    BrowserStop: 0xA9,
    BrowserSearch: 0xAA,
    BrowserFavorites: 0xAB,
    BrowserHome: 0xAC,
    VolumeMute: 0xAD,
    VolumeDown: 0xAE,
    VolumeUp: 0xAF,
    MediaNextTrack: 0xB0,
    MediaPrevTrack: 0xB1,
    MediaStop: 0xB2,
    LaunchMail: 0xB4,
    LaunchMediaSelect: 0xB5,
    LaunchApp1: 0xB6,
    LaunchApp2: 0xB7,
    Oem1: 0xBA,
    OemPlus: 0xBB,
    OemComma: 0xBC,
    OemMinus: 0xBD,
    OemPeriod: 0xBE,
    Oem2: 0xBF,
    Oem3: 0xC0,
    Oem4: 0xDB,
    Oem5: 0xDC,
    Oem6: 0xDD,
    Oem7: 0xDE
} as const;

export const VkToDom: { [ Index in VK ]: FDomKey } =
{
    BrowserBack: "BrowserBack",
    BrowserHome: "BrowserHome",
    BrowserFavorites: "BrowserFavorites",
    BrowserForward: "BrowserForward",
    BrowserRefresh: "BrowserRefresh",
    BrowserSearch: "BrowserSearch",
    BrowserStop: "BrowserStop",
    LButton: "",
    RButton: "",
    MButton: "",
    XButton1: "",
    XButton2: "",
    Back: "Backspace",
    Tab: "Tab",
    Return: "Enter",
    Shift: "ShiftLeft",
    Control: "ControlLeft",
    Menu: "AltLeft",
    Pause: "Pause",
    Capital: "CapsLock",
    Space: "Space",
    Prior: "PageUp",
    Next: "PageDown",
    End: "End",
    Home: "Home",
    Left: "ArrowLeft",
    Up: "ArrowUp",
    Right: "ArrowRight",
    Down: "ArrowDown",
    Select: "",
    Print: "",
    Snapshot: "PrintScreen",
    Insert: "Insert",
    Delete: "Delete",
    "0": "Digit0",
    "1": "Digit1",
    "2": "Digit2",
    "3": "Digit3",
    "4": "Digit4",
    "5": "Digit5",
    "6": "Digit6",
    "7": "Digit7",
    "8": "Digit8",
    "9": "Digit9",
    A: "KeyA",
    B: "KeyB",
    C: "KeyC",
    D: "KeyD",
    E: "KeyE",
    F: "KeyF",
    G: "KeyG",
    H: "KeyH",
    I: "KeyI",
    J: "KeyJ",
    K: "KeyK",
    L: "KeyL",
    M: "KeyM",
    N: "KeyN",
    O: "KeyO",
    P: "KeyP",
    Q: "KeyQ",
    R: "KeyR",
    S: "KeyS",
    T: "KeyT",
    U: "KeyU",
    V: "KeyV",
    W: "KeyW",
    X: "KeyX",
    Y: "KeyY",
    Z: "KeyZ",
    LWin: "MetaLeft",
    RWin: "MetaRight",
    Apps: "ContextMenu",
    NumPad0: "Numpad0",
    NumPad1: "Numpad1",
    NumPad2: "Numpad2",
    NumPad3: "Numpad3",
    NumPad4: "Numpad4",
    NumPad5: "Numpad5",
    NumPad6: "Numpad6",
    NumPad7: "Numpad7",
    NumPad8: "Numpad8",
    NumPad9: "Numpad9",
    Multiply: "NumpadMultiply",
    Add: "NumpadAdd",
    Separator: "",
    Subtract: "NumpadSubtract",
    Decimal: "NumpadDecimal",
    Divide: "NumpadDivide",
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    F13: "F13",
    F14: "F14",
    F15: "F15",
    F16: "F16",
    F17: "F17",
    F18: "F18",
    F19: "F19",
    F20: "F20",
    F21: "F21",
    F22: "F22",
    F23: "F23",
    F24: "F24",
    NumLock: "NumLock",
    Scroll: "ScrollLock",
    LShift: "ShiftLeft",
    RShift: "ShiftRight",
    LControl: "ControlLeft",
    RControl: "ControlRight",
    LMenu: "AltLeft",
    RMenu: "AltRight",
    VolumeMute: "AudioVolumeMute",
    VolumeDown: "AudioVolumeDown",
    VolumeUp: "AudioVolumeUp",
    MediaNextTrack: "MediaTrackNext",
    MediaPrevTrack: "MediaTrackPrevious",
    MediaStop: "MediaStop",
    LaunchMail: "LaunchMail",
    LaunchMediaSelect: "MediaSelect",
    LaunchApp1: "LaunchApp1",
    LaunchApp2: "LaunchApp2",
    Oem1: "Semicolon",
    OemPlus: "Equal",
    OemComma: "Comma",
    OemMinus: "Minus",
    OemPeriod: "Period",
    Oem2: "Slash",
    Oem3: "Backquote",
    Oem4: "BracketLeft",
    Oem5: "Backslash",
    Oem6: "BracketRight",
    Oem7: "Quote"
    
} as const;

/** The DOM codes that do *not* have VK representations. */
type FDomNotInVk =
    | ""
    | "Separator"
    | "Print"
    | "Escape"
    | "NumpadEqual"
    | "NumpadComma"
    | "NumpadEnter"
    | "MediaPlayPause"
    | "IntlBackslash";

export const DomToVk: { [ Index in Exclude<FDomKey, FDomNotInVk> ]: VK } =
{
    "BrowserBack": "BrowserBack",
    "BrowserHome": "BrowserHome",
    "BrowserFavorites": "BrowserFavorites",
    "BrowserForward": "BrowserForward",
    "BrowserRefresh": "BrowserRefresh",
    "BrowserSearch": "BrowserSearch",
    "BrowserStop": "BrowserStop",
    "Backspace": "Back",
    "Tab": "Tab",
    "Enter": "Return",
    "ShiftLeft": "Shift",
    "ControlLeft": "Control",
    "AltLeft": "Menu",
    "Pause": "Pause",
    "CapsLock": "Capital",
    "Space": "Space",
    "PageUp": "Prior",
    "PageDown": "Next",
    "End": "End",
    "Home": "Home",
    "ArrowLeft": "Left",
    "ArrowUp": "Up",
    "ArrowRight": "Right",
    "ArrowDown": "Down",
    "PrintScreen": "Snapshot",
    "Insert": "Insert",
    "Delete": "Delete",
    "Digit0": "0",
    "Digit1": "1",
    "Digit2": "2",
    "Digit3": "3",
    "Digit4": "4",
    "Digit5": "5",
    "Digit6": "6",
    "Digit7": "7",
    "Digit8": "8",
    "Digit9": "9",
    "KeyA": "A",
    "KeyB": "B",
    "KeyC": "C",
    "KeyD": "D",
    "KeyE": "E",
    "KeyF": "F",
    "KeyG": "G",
    "KeyH": "H",
    "KeyI": "I",
    "KeyJ": "J",
    "KeyK": "K",
    "KeyL": "L",
    "KeyM": "M",
    "KeyN": "N",
    "KeyO": "O",
    "KeyP": "P",
    "KeyQ": "Q",
    "KeyR": "R",
    "KeyS": "S",
    "KeyT": "T",
    "KeyU": "U",
    "KeyV": "V",
    "KeyW": "W",
    "KeyX": "X",
    "KeyY": "Y",
    "KeyZ": "Z",
    "MetaLeft": "LWin",
    "MetaRight": "RWin",
    "ContextMenu": "Apps",
    "Numpad0": "NumPad0",
    "Numpad1": "NumPad1",
    "Numpad2": "NumPad2",
    "Numpad3": "NumPad3",
    "Numpad4": "NumPad4",
    "Numpad5": "NumPad5",
    "Numpad6": "NumPad6",
    "Numpad7": "NumPad7",
    "Numpad8": "NumPad8",
    "Numpad9": "NumPad9",
    "NumpadMultiply": "Multiply",
    "NumpadAdd": "Add",
    "NumpadSubtract": "Subtract",
    "NumpadDecimal": "Decimal",
    "NumpadDivide": "Divide",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
    "F13": "F13",
    "F14": "F14",
    "F15": "F15",
    "F16": "F16",
    "F17": "F17",
    "F18": "F18",
    "F19": "F19",
    "F20": "F20",
    "F21": "F21",
    "F22": "F22",
    "F23": "F23",
    "F24": "F24",
    "NumLock": "NumLock",
    "ScrollLock": "Scroll",
    "ShiftRight": "RShift",
    "ControlRight": "RControl",
    "AltRight": "RMenu",
    "AudioVolumeMute": "VolumeMute",
    "AudioVolumeDown": "VolumeDown",
    "AudioVolumeUp": "VolumeUp",
    "MediaTrackNext": "MediaNextTrack",
    "MediaTrackPrevious": "MediaPrevTrack",
    "MediaStop": "MediaStop",
    "LaunchMail": "LaunchMail",
    "MediaSelect": "LaunchMediaSelect",
    "LaunchApp1": "LaunchApp1",
    "LaunchApp2": "LaunchApp2",
    "Semicolon": "Oem1",
    "Equal": "OemPlus",
    "Comma": "OemComma",
    "Minus": "OemMinus",
    "Period": "OemPeriod",
    "Slash": "Oem2",
    "Backquote": "Oem3",
    "BracketLeft": "Oem4",
    "Backslash": "Oem5",
    "BracketRight": "Oem6",
    "Quote": "Oem7"
} as const;